tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "ngrok/ngrok"

brew "autopep8"
brew "go"
brew "mysql", restart_service: true
brew "neofetch"
brew "neovim"
brew "pipenv"
brew "redis", restart_service: true
brew "ripgrep"
cask "ngrok"
cask "iterm2"
brew "pyenv"
brew "git"
brew "wget"
brew "postgresql@14"
brew "go"
brew "lazygit"
brew "neovide"
brew "hugo"
brew "fish"
brew "gsed"

# apps i use on daily basis
cask "discord"
cask "microsoft-teams"
cask "spotify"
cask "google-chrome"
cask "telegram"
cask "notion"
cask "insomnia"
cask "slack"
cask "docker"
